"""add employee date_of_birth and address

Revision ID: 064d3649a4ac
Revises: 0a7f56769069
Create Date: 2026-09-03 22:35:23.337689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '064d3649a4ac'
down_revision = '0a7f56769069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###
