"""add task soft delete

Revision ID: 0a7f56769069
Revises: 02c6d35757d3
Create Date: 2026-09-03 22:15:40.134996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a7f56769069'
down_revision = '02c6d35757d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('deleted_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('deleted_date')
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
