"""add task attachment

Revision ID: 20368560d5c2
Revises: 9c09f2f40362
Create Date: 2026-09-03 20:58:13.161596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20368560d5c2'
down_revision = '9c09f2f40362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_file_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('attachment_file_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('attachment_file_name')
        batch_op.drop_column('attachment_file_url')

    # ### end Alembic commands ###
