"""add user registration detail fields

Revision ID: 4409970f0bbe
Revises: a7fafb35e964
Create Date: 2026-09-02 09:09:14.523107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4409970f0bbe'
down_revision = 'a7fafb35e964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('requested_department', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('requested_position', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('requested_position')
        batch_op.drop_column('requested_department')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
