"""add user status

Revision ID: 610b77c5eda3
Revises: 838292d213fc
Create Date: 2026-09-01 21:44:05.361283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '610b77c5eda3'
down_revision = '838292d213fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='active', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
