"""add employee personal_email

Revision ID: a4dbfda45055
Revises: e4b8a1c9d2f3
Create Date: 2026-09-09 22:47:36.324473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4dbfda45055'
down_revision = 'e4b8a1c9d2f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personal_email', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('personal_email')

    # ### end Alembic commands ###
