"""add task completion report attachment

Revision ID: d1efd3f7b793
Revises: 610b77c5eda3
Create Date: 2026-09-01 22:06:25.422682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1efd3f7b793'
down_revision = '610b77c5eda3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completion_report_file_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('completion_report_file_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('completion_report_file_name')
        batch_op.drop_column('completion_report_file_url')

    # ### end Alembic commands ###
