import { jsPDF } from "jspdf";

function download(filename, content, mime) {
  const blob = new Blob([content], { type: `${mime};charset=utf-8;` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function escapeCSV(val) {
  if (val === null || val === undefined) return "";
  const s = String(val);
  if (/[",\n]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

export function exportCSV(filename, rows, columns) {
  const header = columns.map((c) => escapeCSV(c.label)).join(",");
  const lines = rows.map((row) =>
    columns.map((c) => escapeCSV(row[c.key])).join(",")
  );
  download(filename, [header, ...lines].join("\n"), "text/csv");
}

export function exportPerformancePDF({ employee, perf, period, label }) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const now = new Date();
  const left = 14;
  let y = 20;

  // Header band
  doc.setFillColor(30, 41, 59);
  doc.rect(0, 0, 210, 28, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("Performance Report", left, 13);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`Epic International Consultants`, left, 20);
  doc.text(`Generated: ${now.toLocaleDateString()}`, left, 25);

  y = 40;
  doc.setTextColor(30, 41, 59);

  // Employee info
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text(employee?.full_name || "—", left, y);
  y += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(`Position: ${employee?.position || employee?.role || "—"}`, left, y); y += 5;
  doc.text(`Department: ${employee?.department_name || "—"}`, left, y); y += 5;
  doc.text(`Report Period: ${period} — ${label || ""}`, left, y); y += 5;
  doc.text(`Classification: ${perf.classification}`, left, y); y += 10;

  // Score box
  doc.setFillColor(245, 247, 250);
  doc.roundedRect(left, y, 60, 26, 2, 2, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text(String(perf.score), left + 8, y + 14);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text("/ 100", left + 8, y + 21);
  doc.text("Overall Score", left + 32, y + 11);
  doc.text(`Productivity: ${perf.productivity}%`, left + 32, y + 17);
  doc.text(`On-Time Rate: ${perf.onTimeRate}%`, left + 32, y + 23);
  y += 34;

  // Metrics table
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("Task Metrics", left, y); y += 5;
  doc.setDrawColor(226, 232, 240);
  doc.setFontSize(9);
  const metrics = [
    ["Tasks Assigned", perf.assigned],
    ["Tasks Completed", perf.completed],
    ["Completed On Time", perf.onTime],
    ["Completed Late", perf.late],
    ["Pending / In Progress", perf.pending],
    ["Overdue", perf.overdue],
    ["Archived", perf.archived],
  ];
  doc.line(left, y - 1, 196, y - 1);
  doc.setFont("helvetica", "normal");
  metrics.forEach((m) => {
    doc.text(m[0], left, y);
    doc.text(String(m[1]), 170, y);
    y += 5;
  });
  doc.line(left, y - 1, 196, y - 1);

  // Footer
  doc.setFontSize(7);
  doc.setTextColor(148, 163, 184);
  doc.text(
    "Confidential — Internal use only. Generated by EpicOps.",
    left, 285
  );

  doc.save(`Performance_${(employee?.full_name || "report").replace(/\s+/g, "_")}.pdf`);
}